# Copyright (c) 2016 Bluespec, Inc. All Rights Reserved.

# ================================================================
# Please select one of the TOPMODs below
# (or set it as an environment variable)

TOPMOD ?= mkTestbench

# ================================================================

TOPFILE ?= src_BSV/Testbench.bsv
EXEFILE ?= exe

# ================================================================

include ../Common/Makefile
